### ISSUE TITLE
git-clone fails with results.commit.path: not found

### ISSUE THREAD

**Issue by holly-cummins** [tektoncd/catalog#228] opened 2020-03-18 17:53 UTC
# Expected Behavior

I'm seeing unexpected errors in the execution of a git-clone task. 

# Actual Behavior

The task execution fails with the following error:
```
/tekton/scripts/script-0-xdcr2: line 40: results.commit.path: not found
/tekton/scripts/script-0-xdcr2: line 40: can't create : nonexistent directory
```
# Steps to Reproduce the Problem

This is the relevant snippet of my `pipeline.yml`:

```
    - name: pipeline-fetch-repository-task
      taskRef:
       name: git-clone
      params:
        - name: url
          value: $(params.repository)
        - name: subdirectory
          value: pipeline-checkout
      workspaces:
       - name: output
         workspace: shared-workspace  
```

# Additional Info

I've done a local workaround by commenting out line 40.

**Comment by sbwsg** [comment] 2020-03-18 18:08
Are you on pipelines 0.10 or below?  This is probably the same problem as mentioned here: https://github.com/tektoncd/catalog/issues/224#issuecomment-600032962

The git-clone task is only compatible with 0.11.  I've added a comment to the readme to indicate this but we also plan to introduce some kind of versioning scheme so that this is more obvious for users going forward.  Apologies for the confusion.

I'm going to close this as a likely duplicate of #224 but please feel free to reopen if you don't think it is.

/close

**Closed by sbwsg** 2020-03-18 18:08 UTC

**Comment by holly-cummins** [comment] 2020-03-18 19:09
I agree this is the same issue - I'd checked the existing issues but obviously not carefully enough (and #224 doesn't seem to have been indexed by search engines yet). Thanks for the pointer!
