### ISSUE TITLE
kn task: generateName doesn't work on v0.5.2

### ISSUE THREAD

**Issue by zroubalik** [tektoncd/catalog#58] opened 2019-08-09 12:10 UTC
# Expected Behavior
TaskRun being created

# Actual Behavior
TaskRun is not being created

# Steps to Reproduce the Problem

1. Create task without any modifications from https://github.com/tektoncd/catalog/tree/master/kn
2. Create TaskRun as advised in Readme.md, but got error:
```
$ oc apply -f kn-run.yaml                                                  
error: error when retrieving current configuration of:
Resource: "tekton.dev/v1alpha1, Resource=taskruns", GroupVersionKind: "tekton.dev/v1alpha1, Kind=TaskRun"
Name: "", Namespace: "test-pipelines"
Object: &{map["apiVersion":"tekton.dev/v1alpha1" "kind":"TaskRun" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "generateName":"kn-create-" "namespace":"test-pipelines"] "spec":map["inputs":map["params":[map["name":"service" "value":"my-service"]] "resources":[map["name":"image" "resourceSpec":map["params":[map["name":"url" "value":"gcr.io/knative-samples/helloworld-go"]] "type":"image"]]]] "serviceAccount":"kn-deployer-account" "taskRef":map["name":"kn-create"]]]}
```
3. I had to change `Metadata` in Task from:
```
metadata:
  generateName: kn-create-
```
to:
```
metadata:
  name: kn-create
```

# Additional Info
Running on OpenShift 4.1
(Kubernetes v1.13.4+3a25c9b)
Using Openshift-Pipelines Operator v 0.5.2

**Comment by vdemeester** [comment] 2019-08-13 17:37
@zroubalik thanks for the issue. If you are using `generateName` (as the README suggest), you **have to** use `kubectl create` (or `oc create`) instead of `apply`. `generateName` is a feature of the kubernetes api server, but it only works on `kubectl create` not on apply.

As this is not a bug on pipeline or the task itself, and as it's correctly using `kubectl create` in the README, I'm gonna close this issue.
/close

**Closed by vdemeester** 2019-08-13 17:37 UTC
