### ISSUE TITLE
Add context parameter to buildah

### ISSUE THREAD

**Issue by hrishin** [tektoncd/catalog#202] opened 2020-02-28 05:10 UTC
# Expected Behavior
Add `context`  parameter along with `Dockerfile` parameter. 

# Actual Behavior
Right now `Task` accepts only `Dockerfile` parameter

/kind feature

**Comment by piyush-garg** [comment] 2020-02-28 06:33
Duplicate of #112  and #170 Also the PR #171 is merged do you mean something else?

**Closed** 2020-02-28 06:38 UTC
Labels: kind/feature
